name: Upload Website
 
on:
  push:
    branches:
    - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
      env:
        AWS_S3_BUCKET: s3://mmyterraformprojectwebsite2023
        AWS_ACCESS_KEY_ID: AKIA3FLDXKK77XDWH5HT
        AWS_SECRET_ACCESS_KEY: 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
