name: Upload Website
 
on:
  push:
    branches:
    - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: aws s3 cp ./index.html s3://my-bucket-names/index.html --acl bucket-owner-full-control
aws s3 cp ./README.md s3://my-bucket-names/README.md --acl bucket-owner-full-control
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
