name: Upload Website
 
on:
  push:
    branches:
    - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        AWS_S3_BUCKET: "firstbucket"
        AWS_ACCESS_KEY_ID: AKIA3FLDXKK77XDWH5HT
        AWS_SECRET_ACCESS_KEY: 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
        
    steps:
    - uses: actions/checkout@master
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

     
